plugins {
    id("gov.tak.gradle.plugins.coverage-report-aggregator") version "2.0.0"
}

allprojects {
    group 'me.darknet'
    version '3.0.0'
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'jacoco'

    compileJava.options.encoding = "UTF-8"
    compileJava.options.incremental = true

    compileTestJava.options.encoding = "UTF-8"

    repositories {
        mavenCentral()
        mavenLocal()
        maven { url 'https://jitpack.io' }
    }

    apply plugin: 'maven-publish'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }

        withSourcesJar()
    }

    test {
        useJUnitPlatform()

        testLogging {
            events "passed", "skipped", "failed"
        }

        finalizedBy jacocoTestReport
    }

    jacocoTestReport {
        reports {
            xml.required = true
            csv.required = false
            html.required = true
        }
    }

    dependencies {
        // jetbrains annotations
        implementation 'org.jetbrains:annotations:22.0.0'

        // test dependencies
        testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }

    publishing {
        repositories {
            mavenLocal()
            maven {
                name = 'sources-repo'
                url = 'file:///tmp/sources-repo'
            }
        }
        publications {
            maven(MavenPublication) {
                from components.java
            }
        }
    }

    plugins.withType(JavaPlugin).configureEach {
        dependencies {
            testImplementation platform('org.junit:junit-bom:5.11.4')
            testImplementation 'org.junit.jupiter:junit-jupiter'
        }
    }
}

jacocoAggregation {
    outputHtml = true
    outputXml = true
}

// Build aggregate report for test coverage when subproject 'test' tasks complete.
// But only do so when the 'test' tasks have executed.
// You can skip tests by specifying '-x test' in your gradle task arguments.
tasks.register('test') {
    dependsOn(subprojects.test)
    doLast {
        if (subprojects.test.stream().anyMatch(Task::getDidWork))
            buildJacocoAggregate.execute()
    }
}