apply plugin: 'java-library'
apply plugin: 'java-test-fixtures'

repositories {
    mavenLocal()
    mavenCentral()
    maven { url = 'https://jitpack.io' }
}

dependencies {
    implementation 'org.ow2.asm:asm:9.8'
    implementation 'org.ow2.asm:asm-util:9.8'
    api project(path: ':jasm-core')
    testFixturesImplementation 'org.benf:cfr:0.152'
    testFixturesImplementation 'org.ow2.asm:asm:9.8'
    testFixturesImplementation 'org.ow2.asm:asm-util:9.8'
    testFixturesImplementation 'org.junit.jupiter:junit-jupiter-api:5.11.4'
    testFixturesImplementation(testFixtures(project(path: ':jasm-core')))
    testImplementation(testFixtures(project(path: ':jasm-core')))
}
