apply plugin: 'java-library'

repositories {
    mavenLocal()
    mavenCentral()
    maven { url = 'https://jitpack.io' }
}

dependencies {
    api 'com.github.jumanji144.dex:dex-core:ecf4e82e3f' // 'me.darknet:dex-core:0.0.3-alpha'

    api project(path: ':jasm-core')
    testImplementation(testFixtures(project(path: ':jasm-core')))
}

test {
    useJUnitPlatform()
}
