package me.darknet.assembler.compile;

import me.darknet.assembler.ast.primitive.ASTInstruction;
import me.darknet.assembler.compile.analysis.AnalysisResults;
import me.darknet.assembler.compile.analysis.MethodAnalysisResult;
import me.darknet.assembler.compile.builder.JvmClassBuilder;
import me.darknet.assembler.compiler.InheritanceChecker;
import me.darknet.assembler.error.ErrorCollector;
import me.darknet.assembler.util.JvmTypeUtils;
import me.darknet.assembler.util.Location;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.Type;
import org.objectweb.asm.tree.AbstractInsnNode;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.MethodNode;
import org.objectweb.asm.tree.analysis.Analyzer;
import org.objectweb.asm.tree.analysis.AnalyzerException;
import org.objectweb.asm.tree.analysis.BasicValue;
import org.objectweb.asm.tree.analysis.SimpleVerifier;
import org.objectweb.asm.util.CheckClassAdapter;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

import static me.darknet.assembler.compile.builder.JvmClassBuilder.methodKey;

/**
 * Utility for verifying generated JVM methods and reporting any verification failures as warnings.
 */
public class JvmVerify {
	/**
	 * Verifies the generated methods in the given class bytecode and collects any verification failures as warnings.
	 *
	 * @param bytes
	 * 		Class bytecode to verify.
	 * @param options
	 * 		Compiler options to use for verification.
	 * @param builder
	 * 		Builder containing the generated methods and their analysis results.
	 * @param collector
	 * 		Collector to which any verification warnings will be added.
	 */
	public static void verifyGeneratedMethods(byte @NotNull [] bytes,
	                                          @NotNull JvmCompilerOptions options,
	                                          @NotNull JvmClassBuilder builder,
	                                          @NotNull ErrorCollector collector) {
		// Skip if verification is disabled or if no methods were generated (no need to verify).
		if (!options.verifyOutput() || builder.getMethodAnalysisResults().isEmpty())
			return;

		ClassNode classNode = new ClassNode();
		new ClassReader(bytes).accept(classNode, 0);

		// Map methods by their unique key (name + descriptor) for easy lookup.
		Map<String, MethodNode> methodsByKey = new HashMap<>();
		for (MethodNode method : classNode.methods)
			methodsByKey.put(methodKey(method.name, method.desc), method);

		// Verify each generated method and collect any verification failures as warnings.
		for (Map.Entry<MethodNode, AnalysisResults> entry : builder.getMethodAnalysisResults().entrySet()) {
			MethodNode method = methodsByKey.get(methodKey(entry.getKey().name, entry.getKey().desc));
			if (method == null)
				continue;

			VerificationFailure verifierFailure = verifyGeneratedMethod(classNode, method, options.inheritanceChecker());
			if (verifierFailure == null)
				continue;

			collector.addWarn(
					"Generated bytecode for `" + method.name + method.desc + "` may fail JVM verification: " + verifierFailure.message(),
					mapVerificationFailureLocation(entry.getValue(), method, verifierFailure)
			);
		}
	}

	/**
	 * @param classNode
	 * 		Declaring class of the given method.
	 * @param method
	 * 		Method to verify.
	 * @param checker
	 * 		Inheritance checker to use for type hierarchy checks during verification.
	 *
	 * @return A {@link VerificationFailure} if the method fails verification, or {@code null} if it passes.
	 */
	private static @Nullable VerificationFailure verifyGeneratedMethod(@NotNull ClassNode classNode,
	                                                                   @NotNull MethodNode method,
	                                                                   @NotNull InheritanceChecker checker) {
		ClassNode verificationNode = new ClassNode();
		try {
			byte[] methodBytes = JvmCompiler.writeClassWithMethod(classNode, method);
			new ClassReader(methodBytes).accept(new CheckClassAdapter(verificationNode, false), ClassReader.SKIP_DEBUG);
			analyzeVerificationMethod(verificationNode, checker);
		} catch (AnalyzerException ex) {
			MethodNode verificationMethod = verificationNode.methods.isEmpty() ? null : verificationNode.methods.getFirst();
			return new VerificationFailure(
					stripExceptionPrefix(ex.getMessage()),
					verificationMethod == null ? -1 : executableInstructionIndex(verificationMethod, ex.node)
			);
		} catch (Throwable t) {
			return new VerificationFailure(summarizeVerifierThrowable(t), -1);
		}

		return null;
	}

	/**
	 * @param classNode
	 * 		Declaring class of the method to analyze.
	 * @param checker
	 * 		Inheritance checker to use for type hierarchy checks during analysis.
	 *
	 * @throws AnalyzerException
	 * 		When the method fails verification.
	 */
	private static void analyzeVerificationMethod(@NotNull ClassNode classNode, @NotNull InheritanceChecker checker) throws AnalyzerException {
		if (classNode.methods.isEmpty())
			return;

		MethodNode method = classNode.methods.getFirst();
		List<Type> interfaces = new ArrayList<>();
		if (classNode.interfaces != null) {
			for (String interfaceName : classNode.interfaces)
				interfaces.add(Type.getObjectType(interfaceName));
		}

		SimpleVerifier verifier = new InheritanceAwareSimpleVerifier(
				Type.getObjectType(classNode.name),
				classNode.superName == null ? null : Type.getObjectType(classNode.superName),
				interfaces,
				(classNode.access & Opcodes.ACC_INTERFACE) != 0,
				checker
		);
		new Analyzer<>(verifier).analyze(classNode.name, method);
	}

	/**
	 * @param results
	 * 		Analysis results of the method being verified.
	 * @param method
	 * 		Method being verified.
	 * @param failure
	 * 		Verification failure information.
	 *
	 * @return The location of the instruction that caused the verification failure, or the first instruction in the method if unknown.
	 */
	private static @NotNull Location mapVerificationFailureLocation(@NotNull AnalysisResults results, @NotNull MethodNode method,
	                                                                @NotNull VerificationFailure failure) {
		if (failure.executableInstructionIndex() >= 0) {
			AbstractInsnNode methodInstruction = executableInstructionAt(method, failure.executableInstructionIndex());
			if (methodInstruction != null) {
				ASTInstruction astInstruction = results.getExecutableInstructionToAstMap().get(methodInstruction);
				if (astInstruction != null && astInstruction.location() != null)
					return astInstruction.location();
			}

			if (results instanceof MethodAnalysisResult methodResult) {
				List<ASTInstruction> executableInstructions = methodResult.getExecutableAstInstructions();
				if (failure.executableInstructionIndex() < executableInstructions.size()) {
					ASTInstruction astInstruction = executableInstructions.get(failure.executableInstructionIndex());
					if (astInstruction != null && astInstruction.location() != null)
						return astInstruction.location();
				}
			}
		}

		return firstMethodLocation(results);
	}

	/**
	 * @param results
	 * 		Analysis results of the method being verified.
	 *
	 * @return The location of the first instruction in the method, or {@link Location#UNKNOWN} if no instructions are present.
	 */
	private static @NotNull Location firstMethodLocation(@NotNull AnalysisResults results) {
		if (results instanceof MethodAnalysisResult methodResult) {
			return methodResult.getExecutableAstInstructions().stream()
					.filter(Objects::nonNull)
					.map(ASTInstruction::location)
					.filter(Objects::nonNull)
					.findFirst()
					.orElse(Location.UNKNOWN);
		}

		return results.getExecutableInstructionToAstMap().values().stream()
				.filter(Objects::nonNull)
				.map(ASTInstruction::location)
				.filter(Objects::nonNull)
				.findFirst()
				.orElse(Location.UNKNOWN);
	}

	private static int executableInstructionIndex(@NotNull MethodNode method, @Nullable AbstractInsnNode targetInstruction) {
		if (targetInstruction == null)
			return -1;

		int executableIndex = 0;
		for (AbstractInsnNode instruction = method.instructions.getFirst(); instruction != null; instruction = instruction.getNext()) {
			if (!JvmCompiler.isExecutable(instruction))
				continue;
			if (instruction == targetInstruction)
				return executableIndex;
			executableIndex++;
		}

		return -1;
	}

	private static @Nullable AbstractInsnNode executableInstructionAt(@NotNull MethodNode method, int targetIndex) {
		if (targetIndex < 0)
			return null;

		int executableIndex = 0;
		for (AbstractInsnNode instruction = method.instructions.getFirst(); instruction != null; instruction = instruction.getNext()) {
			if (!JvmCompiler.isExecutable(instruction))
				continue;
			if (executableIndex == targetIndex)
				return instruction;
			executableIndex++;
		}

		return null;
	}

	private static @NotNull String summarizeVerifierThrowable(@NotNull Throwable t) {
		String message = t.getMessage();
		if (message == null || message.isBlank())
			return t.getClass().getSimpleName();
		return stripExceptionPrefix(message);
	}

	private static @NotNull String stripExceptionPrefix(@NotNull String message) {
		int separator = message.indexOf(": ");
		if (separator > 0) {
			String prefix = message.substring(0, separator);
			if (prefix.endsWith("Exception") || prefix.endsWith("Error"))
				return message.substring(separator + 2);
		}
		return message;
	}

	/**
	 * @param message
	 * 		The verification failure message.
	 * @param executableInstructionIndex
	 * 		Instruction index in {@link MethodNode} of the instruction that caused the verification failure, or {@code -1} if unknown.
	 *
	 * @see AnalysisResults#getExecutableInstructionToAstMap()
	 */
	private record VerificationFailure(@NotNull String message, int executableInstructionIndex) {}

	/**
	 * A {@link SimpleVerifier} that is aware of the inheritance hierarchy of the current class being verified.
	 */
	private static final class InheritanceAwareSimpleVerifier extends SimpleVerifier {
		private static final Type CLONEABLE = Type.getObjectType("java/lang/Cloneable");
		private static final Type SERIALIZABLE = Type.getObjectType("java/io/Serializable");

		private final Type currentClass;
		private final Type currentSuperClass;
		private final List<Type> currentInterfaces;
		private final boolean currentIsInterface;
		private final InheritanceChecker checker;

		/**
		 * @param currentClass
		 * 		The type of the current class being verified.
		 * @param currentSuperClass
		 * 		The type of the current class's superclass, or {@code null} if it has no superclass <i>(We are {@code Object})</i>.
		 * @param currentInterfaces
		 * 		The list of types of the current class's interfaces.
		 * @param currentIsInterface
		 * 		Whether the current class is an interface.
		 * @param checker
		 * 		The inheritance checker to use for type hierarchy checks.
		 */
		private InheritanceAwareSimpleVerifier(@NotNull Type currentClass,
		                                       @Nullable Type currentSuperClass,
		                                       @NotNull List<Type> currentInterfaces,
		                                       boolean currentIsInterface,
		                                       @NotNull InheritanceChecker checker) {
			super(Opcodes.ASM9, currentClass, currentSuperClass, currentInterfaces, currentIsInterface);
			this.currentClass = currentClass;
			this.currentSuperClass = currentSuperClass;
			this.currentInterfaces = currentInterfaces;
			this.currentIsInterface = currentIsInterface;
			this.checker = checker;
		}

		@Override
		protected boolean isSubTypeOf(BasicValue value, BasicValue expected) {
			Type actualType = value.getType();
			Type expectedType = expected.getType();
			if (actualType == null || expectedType == null)
				return actualType == expectedType;
			if (actualType.equals(expectedType))
				return true;
			if (!JvmTypeUtils.isReference(expectedType))
				return super.isSubTypeOf(value, expected);
			return isNullType(actualType) || isReferenceAssignable(expectedType, actualType);
		}

		@Override
		public BasicValue merge(BasicValue value1, BasicValue value2) {
			Type type1 = value1.getType();
			Type type2 = value2.getType();
			if (type1 == null || type2 == null)
				return BasicValue.UNINITIALIZED_VALUE;
			if (type1.equals(type2))
				return value1;
			if (!JvmTypeUtils.isReference(type1) || !JvmTypeUtils.isReference(type2))
				return BasicValue.UNINITIALIZED_VALUE;
			if (isNullType(type1))
				return value2;
			if (isNullType(type2))
				return value1;
			Type mergedType = commonReferenceType(type1, type2);
			return newValue(mergedType);
		}

		private boolean isReferenceAssignable(@NotNull Type targetType, @NotNull Type sourceType) {
			if (targetType.equals(sourceType))
				return true;
			if (isNullType(sourceType))
				return true;
			if (targetType.equals(JvmTypeUtils.OBJECT))
				return JvmTypeUtils.isReference(sourceType);

			if (targetType.equals(currentClass))
				return sourceType.equals(currentClass);
			if (sourceType.equals(currentClass)) {
				if (currentSuperClass != null && isReferenceAssignable(targetType, currentSuperClass))
					return true;
				for (Type currentInterface : currentInterfaces) {
					if (isReferenceAssignable(targetType, currentInterface))
						return true;
				}
				return false;
			}

			if (sourceType.getSort() == Type.ARRAY) {
				if (targetType.getSort() == Type.OBJECT)
					return targetType.equals(CLONEABLE) || targetType.equals(SERIALIZABLE) || targetType.equals(JvmTypeUtils.OBJECT);
				if (targetType.getSort() != Type.ARRAY)
					return false;

				Type sourceComponent = Type.getType(sourceType.getDescriptor().substring(1));
				Type targetComponent = Type.getType(targetType.getDescriptor().substring(1));
				if (JvmTypeUtils.isPrimitive(sourceComponent) || JvmTypeUtils.isPrimitive(targetComponent))
					return sourceComponent.equals(targetComponent);
				return isReferenceAssignable(targetComponent, sourceComponent);
			}

			if (targetType.getSort() == Type.ARRAY)
				return false;

			return checker.isSubclassOf(JvmTypeUtils.internalName(sourceType), JvmTypeUtils.internalName(targetType));
		}

		private @NotNull Type commonReferenceType(@NotNull Type type1, @NotNull Type type2) {
			if (isReferenceAssignable(type1, type2))
				return type1;
			if (isReferenceAssignable(type2, type1))
				return type2;
			if (type1.getSort() == Type.ARRAY && type2.getSort() == Type.ARRAY) {
				Type componentType1 = Type.getType(type1.getDescriptor().substring(1));
				Type componentType2 = Type.getType(type2.getDescriptor().substring(1));
				if (JvmTypeUtils.isPrimitive(componentType1) || JvmTypeUtils.isPrimitive(componentType2))
					return JvmTypeUtils.OBJECT;
				Type mergedComponent = commonReferenceType(componentType1, componentType2);
				return Type.getType('[' + mergedComponent.getDescriptor());
			}
			if (type1.getSort() == Type.ARRAY || type2.getSort() == Type.ARRAY)
				return JvmTypeUtils.OBJECT;

			if (currentIsInterface && (type1.equals(currentClass) || type2.equals(currentClass)))
				return JvmTypeUtils.OBJECT;

			String commonSuperclass = checker.getCommonSuperclass(
					JvmTypeUtils.internalName(type1),
					JvmTypeUtils.internalName(type2)
			);
			return commonSuperclass == null ? JvmTypeUtils.OBJECT : Type.getObjectType(commonSuperclass);
		}

		private static boolean isNullType(@NotNull Type type) {
			return "Lnull;".equals(type.getDescriptor());
		}
	}
}
